[build-system]
requires = ["scikit-build-core>=0.10.0", "pybind11>=2.13.0"]
build-backend = "scikit_build_core.build"

[project]
name = "hello-robot-stretch4-pyhesai-wrapper"
# Versioning follow CalVer (YYYY.MM.DD) for PEP 440 compliance
version = "2026.08.25"
requires-python = ">=3.12"
description = "Python wrapper for Hesai Lidar SDK 2.0 for use with Stretch."
dependencies = [
    "numpy>=2.3.4",
    "rerun-sdk>=0.31.0",
    "pyyaml"
]
readme = { file = "README.md", content-type = "text/markdown" }
authors = [
    { name = "Hello Robot Inc.", email = "support@hello-robot.com" },
]

[project.urls]
Repository = "https://github.com/hello-robot/stretch4_pyhesai_wrapper"

[tool.scikit-build]
cmake.source-dir = "."
cmake.args = ["-DPYBIND11_FINDPYTHON=ON"]
wheel.install-dir = "stretch4_pyhesai_wrapper"
wheel.packages = ["stretch4_pyhesai_wrapper"]

[project.scripts]
stretch_lidar_show = "stretch4_pyhesai_wrapper.tools.stretch_lidar_show:main"
REx_hesai_download_calibration = "stretch4_pyhesai_wrapper.tools.REx_hesai_download_calibration:main"
REx_hesai_show_config = "stretch4_pyhesai_wrapper.tools.REx_hesai_show_config:main"
REx_hesai_set_config = "stretch4_pyhesai_wrapper.tools.REx_hesai_set_config:main"
REx_hesai_upgrade_firmware = "stretch4_pyhesai_wrapper.tools.REx_hesai_upgrade_firmware:main"



