left_lidar:
  correction_file: "${HELLO_FLEET_PATH}/${HELLO_FLEET_ID}/calibration_hesais/left_lidar_calibration.dat"
  ip: "192.168.1.202"
  udp_port: 2378
  ptc_connected: false
  ptc_port: 9347

right_lidar:
  correction_file: "${HELLO_FLEET_PATH}/${HELLO_FLEET_ID}/calibration_hesais/right_lidar_calibration.dat"
  ip: "192.168.1.201"
  udp_port: 2368
  ptc_connected: false
  ptc_port: 9347
